### ISSUE TITLE
TFCNs

### ISSUE THREAD

**Issue by lancy827** [HUANGLIZI/TFCNs#3]
I recently read your paper, I feel that the method is very novel, you have made the code public, I tried to run your code, the parameters are according to the paper, but the run out of the index is far from your paper, I do not know where the problem, I want to ask you where the problem arises, but also want to trouble you to give you the training of the weight file, that file, very Thank you
I look forward to hearing from you!

**Comment by HUANGLIZI** [comment]
Please clarify your question?
